"""Download the Heebo webfont and vendor it into the frontend.

Run once on a machine with internet access; the result is committed. The target
network has no route to fonts.googleapis.com, and a CDN font link there fails
silently — the interface drops to a fallback serif and Hebrew typography falls
apart. Self-hosting is the only option that survives the transfer.

    python scripts/vendor_fonts.py
"""

from __future__ import annotations

import re
import subprocess
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = PROJECT_ROOT / "frontend" / "public" / "fonts"
CSS_OUT = PROJECT_ROOT / "frontend" / "src" / "styles" / "fonts.css"

SOURCE = "https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;600;700;800&display=swap"

# Requesting as a modern browser is what makes Google serve woff2 rather than
# a legacy format.
BROWSER_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

HEADER = """/* Heebo, vendored locally — do not edit by hand.
 *
 * Generated by scripts/vendor_fonts.py. Self-hosted rather than linked from
 * fonts.googleapis.com because the target network cannot reach it; a CDN link
 * fails silently there and drops the whole interface to a fallback serif.
 */

"""


def fetch(url: str) -> bytes:
    """Fetch a URL, falling back to curl.

    Some corporate networks route curl through a proxy that Python's urllib
    does not pick up, so trying both is the difference between this script
    working on a given machine and not.
    """
    request = urllib.request.Request(url, headers={"User-Agent": BROWSER_UA})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return response.read()
    except (urllib.error.URLError, TimeoutError):
        result = subprocess.run(
            ["curl", "-sSL", "--max-time", "60", "-A", BROWSER_UA, url],
            capture_output=True,
            check=False,
        )
        if result.returncode != 0 or not result.stdout:
            raise SystemExit(
                f"could not download {url}\n{result.stderr.decode(errors='replace')}"
            ) from None
        return result.stdout


def main() -> None:
    css = fetch(SOURCE).decode("utf-8")

    # Each @font-face is preceded by a comment naming its unicode subset.
    # Heebo ships as a variable font, so several weights share one file — the
    # dict collapses those duplicates automatically.
    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)
    url_to_subset: dict[str, str] = {}
    for subset, body in blocks:
        match = re.search(r"url\((https://[^)]+\.woff2)\)", body)
        if match:
            url_to_subset.setdefault(match.group(1), subset)

    if not url_to_subset:
        raise SystemExit("no woff2 URLs found; the upstream CSS format may have changed")

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    local_css = css
    for url, subset in sorted(url_to_subset.items(), key=lambda item: item[1]):
        filename = f"heebo-{subset}.woff2"
        data = fetch(url)
        (FONT_DIR / filename).write_bytes(data)
        local_css = local_css.replace(url, f"/fonts/{filename}")
        print(f"  {subset:<12} {len(data):>8,} bytes -> {filename}")

    CSS_OUT.write_text(HEADER + local_css, encoding="utf-8")
    print(f"\nwrote {CSS_OUT.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
